services:
  backend:
    image: devhub-backend:dev
    container_name: devhub-backend
    build:
      context: .
      dockerfile: infra/docker/backend.Dockerfile
      args:
        MODE: dev
    tty: true 
    env_file:
    - .env   
    ports:
      - "8080:8080"
    environment:
      - ENV=development
    volumes:
      - ./backend:/app
      - ./plugins:/app/plugins
      - ./generated:/app/generated
    depends_on:
      - db
      - redis

  frontend:
    image: devhub-frontend:dev
    container_name: devhub-frontend
    tty: true
    build:
      context: .
      dockerfile: infra/docker/frontend.Dockerfile
      args:
        MODE: dev
    env_file:
      - .env    
    ports:
      - "3030:3000"
    environment:
      - ENV=development
    volumes:
      - ./frontend:/app

  db:
    build:
      context: .
      dockerfile: infra/docker/db.Dockerfile
    image: devhub-db:dev
    container_name: devhub-db
    environment:
      POSTGRES_USER: devhub
      POSTGRES_PASSWORD: devhubpass
      POSTGRES_DB: devhub
    env_file:
      - .env  
    ports:
      - "54322:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    build:
      context: ./infra/docker
      dockerfile: redis.Dockerfile
    image: devhub-redis:dev
    container_name: devhub-redis
    ports:
      - "6379:63799"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
