services:
  backend:
    build:
      target: prod
      args:
        MODE: prod
    environment:
      SERVICE_ENV: production
    restart: unless-stopped

  frontend:
    build:
      target: prod
      args:
        MODE: prod
    environment:
      NODE_ENV: production
      NUXT_BACKEND_BASE_URL: http://nginx/api
    restart: unless-stopped

  nginx:
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  db:
    restart: unless-stopped
    ports:
      - "5432:5432"

  redis:
    restart: unless-stopped
    ports:
      - "6379:6379"
