services:
  backend:
    build:
      target: prod
      args:
        MODE: prod
    ports:
      - "8080:8080"
    environment:
      SERVICE_ENV: production
    restart: unless-stopped

  frontend:
    profiles: ["frontend"]
    build:
      target: prod
      args:
        MODE: prod
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
    restart: unless-stopped

  db:
    restart: unless-stopped
    ports:
      - "5432:5432"

  redis:
    restart: unless-stopped
    ports:
      - "6379:6379"
