import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import (  # noqa: E402
    build_scaffold_output,
    normalize_module_path,
    read_int,
    read_payload,
    read_required_str,
    resolve_container_image,
    resolve_service_dir,
    success,
    validate_service_name,
)

SCHEMA_PATH = Path(__file__).with_name("schema.json")


def load_schema() -> dict:
    return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))


def write_go_files(service_dir: Path, module_full: str, service_name: str, port: int, image: str) -> None:
    (service_dir / "go.mod").write_text(
        f"""module {module_full}

go 1.22
""",
        encoding="utf-8",
    )

    (service_dir / "main.go").write_text(
        f"""package main

import (
    "fmt"
    "log"
    "net/http"
    "os"
)

func healthHandler(w http.ResponseWriter, r *http.Request) {{
    w.Header().Set("Content-Type", "application/json")
    w.WriteHeader(http.StatusOK)
    _, _ = w.Write([]byte(`{{"status":"ok","service":"{service_name}"}}`))
}}

func main() {{
    mux := http.NewServeMux()
    mux.HandleFunc("/healthz", healthHandler)

    port := os.Getenv("PORT")
    if port == "" {{
        port = "{port}"
    }}

    addr := ":" + port
    fmt.Printf("starting {service_name} on %s\\n", addr)
    log.Fatal(http.ListenAndServe(addr, mux))
}}
""",
        encoding="utf-8",
    )

    (service_dir / "README.md").write_text(
        f"""# {service_name}

Minimal Go HTTP API generated by DevHub plugin.

## Run

```bash
go run .
```

## Endpoint

- `GET /health`
""",
        encoding="utf-8",
    )

    (service_dir / ".gitignore").write_text(
        """bin/
*.log
""",
        encoding="utf-8",
    )

    (service_dir / "Dockerfile").write_text(
        """FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o server .

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/server ./server
EXPOSE 8080
CMD ["./server"]
""",
        encoding="utf-8",
    )

    k8s_dir = service_dir / "k8s"
    k8s_dir.mkdir(parents=True, exist_ok=True)
    (k8s_dir / "deployment.yaml").write_text(
        f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: {service_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {service_name}
  template:
    metadata:
      labels:
        app: {service_name}
    spec:
      containers:
        - name: {service_name}
          image: {image}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {port}
          env:
            - name: PORT
              value: "{port}"
""",
        encoding="utf-8",
    )
    (k8s_dir / "service.yaml").write_text(
        f"""apiVersion: v1
kind: Service
metadata:
  name: {service_name}
spec:
  selector:
    app: {service_name}
  ports:
    - name: http
      port: {port}
      targetPort: {port}
""",
        encoding="utf-8",
    )
    (k8s_dir / "kustomization.yaml").write_text(
        """apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
""",
        encoding="utf-8",
    )


def main() -> None:
    schema = load_schema()
    payload = read_payload(required_fields=schema.get("required", ["service_name"]))
    properties = schema.get("properties", {})

    service_name = read_required_str(payload, "service_name")
    project_id = str(payload.get("project_id", "")).strip()
    output_dir_raw = str(payload.get("output_dir", "")).strip()
    module_path = str(payload.get("module_path", properties.get("module_path", {}).get("default", "github.com/acme"))).strip()
    port = read_int(
        payload,
        "port",
        default=properties.get("port", {}).get("default", 8080),
        min_value=1,
        max_value=65535,
    )

    if output_dir_raw == "":
        base_dir = Path("/app/generated")
        output_dir_raw = str(base_dir / project_id) if project_id else str(base_dir)

    validate_service_name(service_name)
    service_dir = resolve_service_dir(output_dir_raw, service_name)

    module_full = normalize_module_path(module_path, service_name)
    image = resolve_container_image(payload, service_name)
    write_go_files(service_dir, module_full, service_name, port, image)

    success(build_scaffold_output(service_dir, service_name, payload))


if __name__ == "__main__":
    main()
