import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import (  # noqa: E402
    read_payload,
    read_required_str,
    resolve_service_dir,
    success,
    validate_service_name,
)

SCHEMA_PATH = Path(__file__).with_name("schema.json")


def load_schema() -> dict:
    return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))


def write_files(service_dir: Path, service_name: str, queue_name: str) -> None:
    (service_dir / "requirements.txt").write_text(
        "redis==6.0.0\n",
        encoding="utf-8",
    )

    (service_dir / "worker.py").write_text(
        f"""import os
import time


QUEUE_NAME = os.getenv("QUEUE_NAME", "{queue_name}")


def main() -> None:
    print("starting {service_name} for queue:", QUEUE_NAME)
    while True:
        print("polling queue", QUEUE_NAME)
        time.sleep(5)


if __name__ == "__main__":
    main()
""",
        encoding="utf-8",
    )

    (service_dir / "README.md").write_text(
        f"""# {service_name}

Minimal Python worker generated by DevHub plugin.

## Run

```bash
python3 -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
python worker.py
```
""",
        encoding="utf-8",
    )

    (service_dir / ".gitignore").write_text(
        """.venv/
__pycache__/
*.pyc
""",
        encoding="utf-8",
    )

    (service_dir / "Dockerfile").write_text(
        """FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python", "worker.py"]
""",
        encoding="utf-8",
    )


def main() -> None:
    schema = load_schema()
    payload = read_payload(required_fields=schema.get("required", ["service_name"]))

    service_name = read_required_str(payload, "service_name")
    project_id = str(payload.get("project_id", "")).strip()
    output_dir_raw = str(payload.get("output_dir", "")).strip()
    queue_name = str(payload.get("queue_name", f"{service_name}-jobs")).strip() or f"{service_name}-jobs"

    if output_dir_raw == "":
        base_dir = Path("/app/generated")
        output_dir_raw = str(base_dir / project_id) if project_id else str(base_dir)

    validate_service_name(service_name)
    service_dir = resolve_service_dir(output_dir_raw, service_name)
    write_files(service_dir, service_name, queue_name)

    repo_url = str(payload.get("repo_url") or f"file://{service_dir}")
    success({"repo_url": repo_url, "path": str(service_dir)})


if __name__ == "__main__":
    main()
