//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ApprovalDecisions = newApprovalDecisionsTable("public", "approval_decisions", "")

type approvalDecisionsTable struct {
	postgres.Table

	// Columns
	ID                postgres.ColumnString
	ApprovalRequestID postgres.ColumnString
	DecidedBy         postgres.ColumnString
	Decision          postgres.ColumnString
	Comment           postgres.ColumnString
	CreatedAt         postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ApprovalDecisionsTable struct {
	approvalDecisionsTable

	EXCLUDED approvalDecisionsTable
}

// AS creates new ApprovalDecisionsTable with assigned alias
func (a ApprovalDecisionsTable) AS(alias string) *ApprovalDecisionsTable {
	return newApprovalDecisionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ApprovalDecisionsTable with assigned schema name
func (a ApprovalDecisionsTable) FromSchema(schemaName string) *ApprovalDecisionsTable {
	return newApprovalDecisionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ApprovalDecisionsTable with assigned table prefix
func (a ApprovalDecisionsTable) WithPrefix(prefix string) *ApprovalDecisionsTable {
	return newApprovalDecisionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ApprovalDecisionsTable with assigned table suffix
func (a ApprovalDecisionsTable) WithSuffix(suffix string) *ApprovalDecisionsTable {
	return newApprovalDecisionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newApprovalDecisionsTable(schemaName, tableName, alias string) *ApprovalDecisionsTable {
	return &ApprovalDecisionsTable{
		approvalDecisionsTable: newApprovalDecisionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newApprovalDecisionsTableImpl("", "excluded", ""),
	}
}

func newApprovalDecisionsTableImpl(schemaName, tableName, alias string) approvalDecisionsTable {
	var (
		IDColumn                = postgres.StringColumn("id")
		ApprovalRequestIDColumn = postgres.StringColumn("approval_request_id")
		DecidedByColumn         = postgres.StringColumn("decided_by")
		DecisionColumn          = postgres.StringColumn("decision")
		CommentColumn           = postgres.StringColumn("comment")
		CreatedAtColumn         = postgres.TimestampColumn("created_at")
		allColumns              = postgres.ColumnList{IDColumn, ApprovalRequestIDColumn, DecidedByColumn, DecisionColumn, CommentColumn, CreatedAtColumn}
		mutableColumns          = postgres.ColumnList{ApprovalRequestIDColumn, DecidedByColumn, DecisionColumn, CommentColumn, CreatedAtColumn}
		defaultColumns          = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return approvalDecisionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                IDColumn,
		ApprovalRequestID: ApprovalRequestIDColumn,
		DecidedBy:         DecidedByColumn,
		Decision:          DecisionColumn,
		Comment:           CommentColumn,
		CreatedAt:         CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
