//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ApprovalRequests = newApprovalRequestsTable("public", "approval_requests", "")

type approvalRequestsTable struct {
	postgres.Table

	// Columns
	ID                postgres.ColumnString
	Resource          postgres.ColumnString
	Action            postgres.ColumnString
	ResourceID        postgres.ColumnString
	RequestedBy       postgres.ColumnString
	ProjectID         postgres.ColumnString
	ServiceID         postgres.ColumnString
	Environment       postgres.ColumnString
	Status            postgres.ColumnString
	RequiredApprovals postgres.ColumnInteger
	ApprovedCount     postgres.ColumnInteger
	RejectedCount     postgres.ColumnInteger
	ResolvedAt        postgres.ColumnTimestamp
	CreatedAt         postgres.ColumnTimestamp
	UpdatedAt         postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ApprovalRequestsTable struct {
	approvalRequestsTable

	EXCLUDED approvalRequestsTable
}

// AS creates new ApprovalRequestsTable with assigned alias
func (a ApprovalRequestsTable) AS(alias string) *ApprovalRequestsTable {
	return newApprovalRequestsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ApprovalRequestsTable with assigned schema name
func (a ApprovalRequestsTable) FromSchema(schemaName string) *ApprovalRequestsTable {
	return newApprovalRequestsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ApprovalRequestsTable with assigned table prefix
func (a ApprovalRequestsTable) WithPrefix(prefix string) *ApprovalRequestsTable {
	return newApprovalRequestsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ApprovalRequestsTable with assigned table suffix
func (a ApprovalRequestsTable) WithSuffix(suffix string) *ApprovalRequestsTable {
	return newApprovalRequestsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newApprovalRequestsTable(schemaName, tableName, alias string) *ApprovalRequestsTable {
	return &ApprovalRequestsTable{
		approvalRequestsTable: newApprovalRequestsTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newApprovalRequestsTableImpl("", "excluded", ""),
	}
}

func newApprovalRequestsTableImpl(schemaName, tableName, alias string) approvalRequestsTable {
	var (
		IDColumn                = postgres.StringColumn("id")
		ResourceColumn          = postgres.StringColumn("resource")
		ActionColumn            = postgres.StringColumn("action")
		ResourceIDColumn        = postgres.StringColumn("resource_id")
		RequestedByColumn       = postgres.StringColumn("requested_by")
		ProjectIDColumn         = postgres.StringColumn("project_id")
		ServiceIDColumn         = postgres.StringColumn("service_id")
		EnvironmentColumn       = postgres.StringColumn("environment")
		StatusColumn            = postgres.StringColumn("status")
		RequiredApprovalsColumn = postgres.IntegerColumn("required_approvals")
		ApprovedCountColumn     = postgres.IntegerColumn("approved_count")
		RejectedCountColumn     = postgres.IntegerColumn("rejected_count")
		ResolvedAtColumn        = postgres.TimestampColumn("resolved_at")
		CreatedAtColumn         = postgres.TimestampColumn("created_at")
		UpdatedAtColumn         = postgres.TimestampColumn("updated_at")
		allColumns              = postgres.ColumnList{IDColumn, ResourceColumn, ActionColumn, ResourceIDColumn, RequestedByColumn, ProjectIDColumn, ServiceIDColumn, EnvironmentColumn, StatusColumn, RequiredApprovalsColumn, ApprovedCountColumn, RejectedCountColumn, ResolvedAtColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns          = postgres.ColumnList{ResourceColumn, ActionColumn, ResourceIDColumn, RequestedByColumn, ProjectIDColumn, ServiceIDColumn, EnvironmentColumn, StatusColumn, RequiredApprovalsColumn, ApprovedCountColumn, RejectedCountColumn, ResolvedAtColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns          = postgres.ColumnList{IDColumn, StatusColumn, RequiredApprovalsColumn, ApprovedCountColumn, RejectedCountColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return approvalRequestsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                IDColumn,
		Resource:          ResourceColumn,
		Action:            ActionColumn,
		ResourceID:        ResourceIDColumn,
		RequestedBy:       RequestedByColumn,
		ProjectID:         ProjectIDColumn,
		ServiceID:         ServiceIDColumn,
		Environment:       EnvironmentColumn,
		Status:            StatusColumn,
		RequiredApprovals: RequiredApprovalsColumn,
		ApprovedCount:     ApprovedCountColumn,
		RejectedCount:     RejectedCountColumn,
		ResolvedAt:        ResolvedAtColumn,
		CreatedAt:         CreatedAtColumn,
		UpdatedAt:         UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
