//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ApprovalPolicies = newApprovalPoliciesTable("public", "approval_policies", "")

type approvalPoliciesTable struct {
	postgres.Table

	// Columns
	ID                postgres.ColumnString
	Resource          postgres.ColumnString
	Action            postgres.ColumnString
	ProjectID         postgres.ColumnString
	ServiceID         postgres.ColumnString
	Environment       postgres.ColumnString
	RequiredApprovals postgres.ColumnInteger
	Enabled           postgres.ColumnBool
	CreatedAt         postgres.ColumnTimestamp
	UpdatedAt         postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ApprovalPoliciesTable struct {
	approvalPoliciesTable

	EXCLUDED approvalPoliciesTable
}

// AS creates new ApprovalPoliciesTable with assigned alias
func (a ApprovalPoliciesTable) AS(alias string) *ApprovalPoliciesTable {
	return newApprovalPoliciesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ApprovalPoliciesTable with assigned schema name
func (a ApprovalPoliciesTable) FromSchema(schemaName string) *ApprovalPoliciesTable {
	return newApprovalPoliciesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ApprovalPoliciesTable with assigned table prefix
func (a ApprovalPoliciesTable) WithPrefix(prefix string) *ApprovalPoliciesTable {
	return newApprovalPoliciesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ApprovalPoliciesTable with assigned table suffix
func (a ApprovalPoliciesTable) WithSuffix(suffix string) *ApprovalPoliciesTable {
	return newApprovalPoliciesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newApprovalPoliciesTable(schemaName, tableName, alias string) *ApprovalPoliciesTable {
	return &ApprovalPoliciesTable{
		approvalPoliciesTable: newApprovalPoliciesTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newApprovalPoliciesTableImpl("", "excluded", ""),
	}
}

func newApprovalPoliciesTableImpl(schemaName, tableName, alias string) approvalPoliciesTable {
	var (
		IDColumn                = postgres.StringColumn("id")
		ResourceColumn          = postgres.StringColumn("resource")
		ActionColumn            = postgres.StringColumn("action")
		ProjectIDColumn         = postgres.StringColumn("project_id")
		ServiceIDColumn         = postgres.StringColumn("service_id")
		EnvironmentColumn       = postgres.StringColumn("environment")
		RequiredApprovalsColumn = postgres.IntegerColumn("required_approvals")
		EnabledColumn           = postgres.BoolColumn("enabled")
		CreatedAtColumn         = postgres.TimestampColumn("created_at")
		UpdatedAtColumn         = postgres.TimestampColumn("updated_at")
		allColumns              = postgres.ColumnList{IDColumn, ResourceColumn, ActionColumn, ProjectIDColumn, ServiceIDColumn, EnvironmentColumn, RequiredApprovalsColumn, EnabledColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns          = postgres.ColumnList{ResourceColumn, ActionColumn, ProjectIDColumn, ServiceIDColumn, EnvironmentColumn, RequiredApprovalsColumn, EnabledColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns          = postgres.ColumnList{IDColumn, RequiredApprovalsColumn, EnabledColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return approvalPoliciesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                IDColumn,
		Resource:          ResourceColumn,
		Action:            ActionColumn,
		ProjectID:         ProjectIDColumn,
		ServiceID:         ServiceIDColumn,
		Environment:       EnvironmentColumn,
		RequiredApprovals: RequiredApprovalsColumn,
		Enabled:           EnabledColumn,
		CreatedAt:         CreatedAtColumn,
		UpdatedAt:         UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
