//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Deployments = newDeploymentsTable("public", "deployments", "")

type deploymentsTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	ProjectID   postgres.ColumnString
	Environment postgres.ColumnString
	Service     postgres.ColumnString
	Version     postgres.ColumnString
	Status      postgres.ColumnString
	TriggeredBy postgres.ColumnString
	CreatedAt   postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type DeploymentsTable struct {
	deploymentsTable

	EXCLUDED deploymentsTable
}

// AS creates new DeploymentsTable with assigned alias
func (a DeploymentsTable) AS(alias string) *DeploymentsTable {
	return newDeploymentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DeploymentsTable with assigned schema name
func (a DeploymentsTable) FromSchema(schemaName string) *DeploymentsTable {
	return newDeploymentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DeploymentsTable with assigned table prefix
func (a DeploymentsTable) WithPrefix(prefix string) *DeploymentsTable {
	return newDeploymentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DeploymentsTable with assigned table suffix
func (a DeploymentsTable) WithSuffix(suffix string) *DeploymentsTable {
	return newDeploymentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDeploymentsTable(schemaName, tableName, alias string) *DeploymentsTable {
	return &DeploymentsTable{
		deploymentsTable: newDeploymentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newDeploymentsTableImpl("", "excluded", ""),
	}
}

func newDeploymentsTableImpl(schemaName, tableName, alias string) deploymentsTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		ProjectIDColumn   = postgres.StringColumn("project_id")
		EnvironmentColumn = postgres.StringColumn("environment")
		ServiceColumn     = postgres.StringColumn("service")
		VersionColumn     = postgres.StringColumn("version")
		StatusColumn      = postgres.StringColumn("status")
		TriggeredByColumn = postgres.StringColumn("triggered_by")
		CreatedAtColumn   = postgres.TimestampColumn("created_at")
		allColumns        = postgres.ColumnList{IDColumn, ProjectIDColumn, EnvironmentColumn, ServiceColumn, VersionColumn, StatusColumn, TriggeredByColumn, CreatedAtColumn}
		mutableColumns    = postgres.ColumnList{ProjectIDColumn, EnvironmentColumn, ServiceColumn, VersionColumn, StatusColumn, TriggeredByColumn, CreatedAtColumn}
		defaultColumns    = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return deploymentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		ProjectID:   ProjectIDColumn,
		Environment: EnvironmentColumn,
		Service:     ServiceColumn,
		Version:     VersionColumn,
		Status:      StatusColumn,
		TriggeredBy: TriggeredByColumn,
		CreatedAt:   CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
