//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Deployments = newDeploymentsTable("public", "deployments", "")

type deploymentsTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	ServiceID   postgres.ColumnString
	PluginID    postgres.ColumnString
	Environment postgres.ColumnString
	Version     postgres.ColumnString
	Status      postgres.ColumnString
	ExternalRef postgres.ColumnString
	CommitSha   postgres.ColumnString
	TriggeredBy postgres.ColumnString
	CreatedAt   postgres.ColumnTimestamp
	UpdatedAt   postgres.ColumnTimestamp
	FinishedAt  postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type DeploymentsTable struct {
	deploymentsTable

	EXCLUDED deploymentsTable
}

// AS creates new DeploymentsTable with assigned alias
func (a DeploymentsTable) AS(alias string) *DeploymentsTable {
	return newDeploymentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DeploymentsTable with assigned schema name
func (a DeploymentsTable) FromSchema(schemaName string) *DeploymentsTable {
	return newDeploymentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DeploymentsTable with assigned table prefix
func (a DeploymentsTable) WithPrefix(prefix string) *DeploymentsTable {
	return newDeploymentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DeploymentsTable with assigned table suffix
func (a DeploymentsTable) WithSuffix(suffix string) *DeploymentsTable {
	return newDeploymentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDeploymentsTable(schemaName, tableName, alias string) *DeploymentsTable {
	return &DeploymentsTable{
		deploymentsTable: newDeploymentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newDeploymentsTableImpl("", "excluded", ""),
	}
}

func newDeploymentsTableImpl(schemaName, tableName, alias string) deploymentsTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		ServiceIDColumn   = postgres.StringColumn("service_id")
		PluginIDColumn    = postgres.StringColumn("plugin_id")
		EnvironmentColumn = postgres.StringColumn("environment")
		VersionColumn     = postgres.StringColumn("version")
		StatusColumn      = postgres.StringColumn("status")
		ExternalRefColumn = postgres.StringColumn("external_ref")
		CommitShaColumn   = postgres.StringColumn("commit_sha")
		TriggeredByColumn = postgres.StringColumn("triggered_by")
		CreatedAtColumn   = postgres.TimestampColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampColumn("updated_at")
		FinishedAtColumn  = postgres.TimestampColumn("finished_at")
		allColumns        = postgres.ColumnList{IDColumn, ServiceIDColumn, PluginIDColumn, EnvironmentColumn, VersionColumn, StatusColumn, ExternalRefColumn, CommitShaColumn, TriggeredByColumn, CreatedAtColumn, UpdatedAtColumn, FinishedAtColumn}
		mutableColumns    = postgres.ColumnList{ServiceIDColumn, PluginIDColumn, EnvironmentColumn, VersionColumn, StatusColumn, ExternalRefColumn, CommitShaColumn, TriggeredByColumn, CreatedAtColumn, UpdatedAtColumn, FinishedAtColumn}
		defaultColumns    = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return deploymentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		ServiceID:   ServiceIDColumn,
		PluginID:    PluginIDColumn,
		Environment: EnvironmentColumn,
		Version:     VersionColumn,
		Status:      StatusColumn,
		ExternalRef: ExternalRefColumn,
		CommitSha:   CommitShaColumn,
		TriggeredBy: TriggeredByColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,
		FinishedAt:  FinishedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
