//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Environments = newEnvironmentsTable("public", "environments", "")

type environmentsTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	ProjectID      postgres.ColumnString
	Name           postgres.ColumnString
	Tier           postgres.ColumnString
	Cluster        postgres.ColumnString
	Namespace      postgres.ColumnString
	ArgocdInstance postgres.ColumnString
	Config         postgres.ColumnString
	CreatedAt      postgres.ColumnTimestamp
	UpdatedAt      postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type EnvironmentsTable struct {
	environmentsTable

	EXCLUDED environmentsTable
}

// AS creates new EnvironmentsTable with assigned alias
func (a EnvironmentsTable) AS(alias string) *EnvironmentsTable {
	return newEnvironmentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EnvironmentsTable with assigned schema name
func (a EnvironmentsTable) FromSchema(schemaName string) *EnvironmentsTable {
	return newEnvironmentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EnvironmentsTable with assigned table prefix
func (a EnvironmentsTable) WithPrefix(prefix string) *EnvironmentsTable {
	return newEnvironmentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EnvironmentsTable with assigned table suffix
func (a EnvironmentsTable) WithSuffix(suffix string) *EnvironmentsTable {
	return newEnvironmentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEnvironmentsTable(schemaName, tableName, alias string) *EnvironmentsTable {
	return &EnvironmentsTable{
		environmentsTable: newEnvironmentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newEnvironmentsTableImpl("", "excluded", ""),
	}
}

func newEnvironmentsTableImpl(schemaName, tableName, alias string) environmentsTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		ProjectIDColumn      = postgres.StringColumn("project_id")
		NameColumn           = postgres.StringColumn("name")
		TierColumn           = postgres.StringColumn("tier")
		ClusterColumn        = postgres.StringColumn("cluster")
		NamespaceColumn      = postgres.StringColumn("namespace")
		ArgocdInstanceColumn = postgres.StringColumn("argocd_instance")
		ConfigColumn         = postgres.StringColumn("config")
		CreatedAtColumn      = postgres.TimestampColumn("created_at")
		UpdatedAtColumn      = postgres.TimestampColumn("updated_at")
		allColumns           = postgres.ColumnList{IDColumn, ProjectIDColumn, NameColumn, TierColumn, ClusterColumn, NamespaceColumn, ArgocdInstanceColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns       = postgres.ColumnList{ProjectIDColumn, NameColumn, TierColumn, ClusterColumn, NamespaceColumn, ArgocdInstanceColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns       = postgres.ColumnList{IDColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return environmentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		ProjectID:      ProjectIDColumn,
		Name:           NameColumn,
		Tier:           TierColumn,
		Cluster:        ClusterColumn,
		Namespace:      NamespaceColumn,
		ArgocdInstance: ArgocdInstanceColumn,
		Config:         ConfigColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
