//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Jobs = newJobsTable("public", "jobs", "")

type jobsTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	Type         postgres.ColumnString
	Status       postgres.ColumnString
	ResourceType postgres.ColumnString
	ResourceID   postgres.ColumnString
	PluginID     postgres.ColumnString
	Payload      postgres.ColumnString
	Result       postgres.ColumnString
	Error        postgres.ColumnString
	Attempts     postgres.ColumnInteger
	MaxAttempts  postgres.ColumnInteger
	CreatedBy    postgres.ColumnString
	CreatedAt    postgres.ColumnTimestamp
	UpdatedAt    postgres.ColumnTimestamp
	StartedAt    postgres.ColumnTimestamp
	FinishedAt   postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type JobsTable struct {
	jobsTable

	EXCLUDED jobsTable
}

// AS creates new JobsTable with assigned alias
func (a JobsTable) AS(alias string) *JobsTable {
	return newJobsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new JobsTable with assigned schema name
func (a JobsTable) FromSchema(schemaName string) *JobsTable {
	return newJobsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new JobsTable with assigned table prefix
func (a JobsTable) WithPrefix(prefix string) *JobsTable {
	return newJobsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new JobsTable with assigned table suffix
func (a JobsTable) WithSuffix(suffix string) *JobsTable {
	return newJobsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newJobsTable(schemaName, tableName, alias string) *JobsTable {
	return &JobsTable{
		jobsTable: newJobsTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newJobsTableImpl("", "excluded", ""),
	}
}

func newJobsTableImpl(schemaName, tableName, alias string) jobsTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		TypeColumn         = postgres.StringColumn("type")
		StatusColumn       = postgres.StringColumn("status")
		ResourceTypeColumn = postgres.StringColumn("resource_type")
		ResourceIDColumn   = postgres.StringColumn("resource_id")
		PluginIDColumn     = postgres.StringColumn("plugin_id")
		PayloadColumn      = postgres.StringColumn("payload")
		ResultColumn       = postgres.StringColumn("result")
		ErrorColumn        = postgres.StringColumn("error")
		AttemptsColumn     = postgres.IntegerColumn("attempts")
		MaxAttemptsColumn  = postgres.IntegerColumn("max_attempts")
		CreatedByColumn    = postgres.StringColumn("created_by")
		CreatedAtColumn    = postgres.TimestampColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampColumn("updated_at")
		StartedAtColumn    = postgres.TimestampColumn("started_at")
		FinishedAtColumn   = postgres.TimestampColumn("finished_at")
		allColumns         = postgres.ColumnList{IDColumn, TypeColumn, StatusColumn, ResourceTypeColumn, ResourceIDColumn, PluginIDColumn, PayloadColumn, ResultColumn, ErrorColumn, AttemptsColumn, MaxAttemptsColumn, CreatedByColumn, CreatedAtColumn, UpdatedAtColumn, StartedAtColumn, FinishedAtColumn}
		mutableColumns     = postgres.ColumnList{TypeColumn, StatusColumn, ResourceTypeColumn, ResourceIDColumn, PluginIDColumn, PayloadColumn, ResultColumn, ErrorColumn, AttemptsColumn, MaxAttemptsColumn, CreatedByColumn, CreatedAtColumn, UpdatedAtColumn, StartedAtColumn, FinishedAtColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, ResultColumn, AttemptsColumn, MaxAttemptsColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return jobsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		Type:         TypeColumn,
		Status:       StatusColumn,
		ResourceType: ResourceTypeColumn,
		ResourceID:   ResourceIDColumn,
		PluginID:     PluginIDColumn,
		Payload:      PayloadColumn,
		Result:       ResultColumn,
		Error:        ErrorColumn,
		Attempts:     AttemptsColumn,
		MaxAttempts:  MaxAttemptsColumn,
		CreatedBy:    CreatedByColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,
		StartedAt:    StartedAtColumn,
		FinishedAt:   FinishedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
