//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Plugins = newPluginsTable("public", "plugins", "")

type pluginsTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	Name        postgres.ColumnString
	Version     postgres.ColumnString
	Type        postgres.ColumnString
	Description postgres.ColumnString
	InstalledAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PluginsTable struct {
	pluginsTable

	EXCLUDED pluginsTable
}

// AS creates new PluginsTable with assigned alias
func (a PluginsTable) AS(alias string) *PluginsTable {
	return newPluginsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PluginsTable with assigned schema name
func (a PluginsTable) FromSchema(schemaName string) *PluginsTable {
	return newPluginsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PluginsTable with assigned table prefix
func (a PluginsTable) WithPrefix(prefix string) *PluginsTable {
	return newPluginsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PluginsTable with assigned table suffix
func (a PluginsTable) WithSuffix(suffix string) *PluginsTable {
	return newPluginsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPluginsTable(schemaName, tableName, alias string) *PluginsTable {
	return &PluginsTable{
		pluginsTable: newPluginsTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newPluginsTableImpl("", "excluded", ""),
	}
}

func newPluginsTableImpl(schemaName, tableName, alias string) pluginsTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		NameColumn        = postgres.StringColumn("name")
		VersionColumn     = postgres.StringColumn("version")
		TypeColumn        = postgres.StringColumn("type")
		DescriptionColumn = postgres.StringColumn("description")
		InstalledAtColumn = postgres.TimestampColumn("installed_at")
		allColumns        = postgres.ColumnList{IDColumn, NameColumn, VersionColumn, TypeColumn, DescriptionColumn, InstalledAtColumn}
		mutableColumns    = postgres.ColumnList{NameColumn, VersionColumn, TypeColumn, DescriptionColumn, InstalledAtColumn}
		defaultColumns    = postgres.ColumnList{IDColumn}
	)

	return pluginsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		Version:     VersionColumn,
		Type:        TypeColumn,
		Description: DescriptionColumn,
		InstalledAt: InstalledAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
