//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var RefreshTokens = newRefreshTokensTable("public", "refresh_tokens", "")

type refreshTokensTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	UserID    postgres.ColumnString
	Token     postgres.ColumnString
	CreatedAt postgres.ColumnTimestamp
	ExpiresAt postgres.ColumnTimestamp
	DeletedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type RefreshTokensTable struct {
	refreshTokensTable

	EXCLUDED refreshTokensTable
}

// AS creates new RefreshTokensTable with assigned alias
func (a RefreshTokensTable) AS(alias string) *RefreshTokensTable {
	return newRefreshTokensTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RefreshTokensTable with assigned schema name
func (a RefreshTokensTable) FromSchema(schemaName string) *RefreshTokensTable {
	return newRefreshTokensTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RefreshTokensTable with assigned table prefix
func (a RefreshTokensTable) WithPrefix(prefix string) *RefreshTokensTable {
	return newRefreshTokensTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RefreshTokensTable with assigned table suffix
func (a RefreshTokensTable) WithSuffix(suffix string) *RefreshTokensTable {
	return newRefreshTokensTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRefreshTokensTable(schemaName, tableName, alias string) *RefreshTokensTable {
	return &RefreshTokensTable{
		refreshTokensTable: newRefreshTokensTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newRefreshTokensTableImpl("", "excluded", ""),
	}
}

func newRefreshTokensTableImpl(schemaName, tableName, alias string) refreshTokensTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		UserIDColumn    = postgres.StringColumn("user_id")
		TokenColumn     = postgres.StringColumn("token")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		ExpiresAtColumn = postgres.TimestampColumn("expires_at")
		DeletedAtColumn = postgres.TimestampColumn("deleted_at")
		allColumns      = postgres.ColumnList{IDColumn, UserIDColumn, TokenColumn, CreatedAtColumn, ExpiresAtColumn, DeletedAtColumn}
		mutableColumns  = postgres.ColumnList{UserIDColumn, TokenColumn, CreatedAtColumn, ExpiresAtColumn, DeletedAtColumn}
		defaultColumns  = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return refreshTokensTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		UserID:    UserIDColumn,
		Token:     TokenColumn,
		CreatedAt: CreatedAtColumn,
		ExpiresAt: ExpiresAtColumn,
		DeletedAt: DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
