//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Releases = newReleasesTable("public", "releases", "")

type releasesTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	ServiceID   postgres.ColumnString
	PluginID    postgres.ColumnString
	Tag         postgres.ColumnString
	Target      postgres.ColumnString
	Name        postgres.ColumnString
	Status      postgres.ColumnString
	Notes       postgres.ColumnString
	HTMLURL     postgres.ColumnString
	ExternalRef postgres.ColumnString
	TriggeredBy postgres.ColumnString
	CreatedAt   postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ReleasesTable struct {
	releasesTable

	EXCLUDED releasesTable
}

// AS creates new ReleasesTable with assigned alias
func (a ReleasesTable) AS(alias string) *ReleasesTable {
	return newReleasesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ReleasesTable with assigned schema name
func (a ReleasesTable) FromSchema(schemaName string) *ReleasesTable {
	return newReleasesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ReleasesTable with assigned table prefix
func (a ReleasesTable) WithPrefix(prefix string) *ReleasesTable {
	return newReleasesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ReleasesTable with assigned table suffix
func (a ReleasesTable) WithSuffix(suffix string) *ReleasesTable {
	return newReleasesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newReleasesTable(schemaName, tableName, alias string) *ReleasesTable {
	return &ReleasesTable{
		releasesTable: newReleasesTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newReleasesTableImpl("", "excluded", ""),
	}
}

func newReleasesTableImpl(schemaName, tableName, alias string) releasesTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		ServiceIDColumn   = postgres.StringColumn("service_id")
		PluginIDColumn    = postgres.StringColumn("plugin_id")
		TagColumn         = postgres.StringColumn("tag")
		TargetColumn      = postgres.StringColumn("target")
		NameColumn        = postgres.StringColumn("name")
		StatusColumn      = postgres.StringColumn("status")
		NotesColumn       = postgres.StringColumn("notes")
		HTMLURLColumn     = postgres.StringColumn("html_url")
		ExternalRefColumn = postgres.StringColumn("external_ref")
		TriggeredByColumn = postgres.StringColumn("triggered_by")
		CreatedAtColumn   = postgres.TimestampColumn("created_at")
		allColumns        = postgres.ColumnList{IDColumn, ServiceIDColumn, PluginIDColumn, TagColumn, TargetColumn, NameColumn, StatusColumn, NotesColumn, HTMLURLColumn, ExternalRefColumn, TriggeredByColumn, CreatedAtColumn}
		mutableColumns    = postgres.ColumnList{ServiceIDColumn, PluginIDColumn, TagColumn, TargetColumn, NameColumn, StatusColumn, NotesColumn, HTMLURLColumn, ExternalRefColumn, TriggeredByColumn, CreatedAtColumn}
		defaultColumns    = postgres.ColumnList{IDColumn, NotesColumn, CreatedAtColumn}
	)

	return releasesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		ServiceID:   ServiceIDColumn,
		PluginID:    PluginIDColumn,
		Tag:         TagColumn,
		Target:      TargetColumn,
		Name:        NameColumn,
		Status:      StatusColumn,
		Notes:       NotesColumn,
		HTMLURL:     HTMLURLColumn,
		ExternalRef: ExternalRefColumn,
		TriggeredBy: TriggeredByColumn,
		CreatedAt:   CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
