//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var RolePermissions = newRolePermissionsTable("public", "role_permissions", "")

type rolePermissionsTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	RoleID       postgres.ColumnString
	PermissionID postgres.ColumnString
	CreatedAt    postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type RolePermissionsTable struct {
	rolePermissionsTable

	EXCLUDED rolePermissionsTable
}

// AS creates new RolePermissionsTable with assigned alias
func (a RolePermissionsTable) AS(alias string) *RolePermissionsTable {
	return newRolePermissionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RolePermissionsTable with assigned schema name
func (a RolePermissionsTable) FromSchema(schemaName string) *RolePermissionsTable {
	return newRolePermissionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RolePermissionsTable with assigned table prefix
func (a RolePermissionsTable) WithPrefix(prefix string) *RolePermissionsTable {
	return newRolePermissionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RolePermissionsTable with assigned table suffix
func (a RolePermissionsTable) WithSuffix(suffix string) *RolePermissionsTable {
	return newRolePermissionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRolePermissionsTable(schemaName, tableName, alias string) *RolePermissionsTable {
	return &RolePermissionsTable{
		rolePermissionsTable: newRolePermissionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newRolePermissionsTableImpl("", "excluded", ""),
	}
}

func newRolePermissionsTableImpl(schemaName, tableName, alias string) rolePermissionsTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		RoleIDColumn       = postgres.StringColumn("role_id")
		PermissionIDColumn = postgres.StringColumn("permission_id")
		CreatedAtColumn    = postgres.TimestampColumn("created_at")
		allColumns         = postgres.ColumnList{IDColumn, RoleIDColumn, PermissionIDColumn, CreatedAtColumn}
		mutableColumns     = postgres.ColumnList{RoleIDColumn, PermissionIDColumn, CreatedAtColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return rolePermissionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		RoleID:       RoleIDColumn,
		PermissionID: PermissionIDColumn,
		CreatedAt:    CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
