//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ScaffoldRequests = newScaffoldRequestsTable("public", "scaffold_requests", "")

type scaffoldRequestsTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	ProjectID     postgres.ColumnString
	RequestedBy   postgres.ColumnString
	ApprovedBy    postgres.ColumnString
	Status        postgres.ColumnString
	Variables     postgres.ColumnString
	ResultRepoURL postgres.ColumnString
	ApprovedAt    postgres.ColumnTimestamp
	CreatedAt     postgres.ColumnTimestamp
	UpdatedAt     postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ScaffoldRequestsTable struct {
	scaffoldRequestsTable

	EXCLUDED scaffoldRequestsTable
}

// AS creates new ScaffoldRequestsTable with assigned alias
func (a ScaffoldRequestsTable) AS(alias string) *ScaffoldRequestsTable {
	return newScaffoldRequestsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ScaffoldRequestsTable with assigned schema name
func (a ScaffoldRequestsTable) FromSchema(schemaName string) *ScaffoldRequestsTable {
	return newScaffoldRequestsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ScaffoldRequestsTable with assigned table prefix
func (a ScaffoldRequestsTable) WithPrefix(prefix string) *ScaffoldRequestsTable {
	return newScaffoldRequestsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ScaffoldRequestsTable with assigned table suffix
func (a ScaffoldRequestsTable) WithSuffix(suffix string) *ScaffoldRequestsTable {
	return newScaffoldRequestsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newScaffoldRequestsTable(schemaName, tableName, alias string) *ScaffoldRequestsTable {
	return &ScaffoldRequestsTable{
		scaffoldRequestsTable: newScaffoldRequestsTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newScaffoldRequestsTableImpl("", "excluded", ""),
	}
}

func newScaffoldRequestsTableImpl(schemaName, tableName, alias string) scaffoldRequestsTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		ProjectIDColumn     = postgres.StringColumn("project_id")
		RequestedByColumn   = postgres.StringColumn("requested_by")
		ApprovedByColumn    = postgres.StringColumn("approved_by")
		StatusColumn        = postgres.StringColumn("status")
		VariablesColumn     = postgres.StringColumn("variables")
		ResultRepoURLColumn = postgres.StringColumn("result_repo_url")
		ApprovedAtColumn    = postgres.TimestampColumn("approved_at")
		CreatedAtColumn     = postgres.TimestampColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampColumn("updated_at")
		allColumns          = postgres.ColumnList{IDColumn, ProjectIDColumn, RequestedByColumn, ApprovedByColumn, StatusColumn, VariablesColumn, ResultRepoURLColumn, ApprovedAtColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{ProjectIDColumn, RequestedByColumn, ApprovedByColumn, StatusColumn, VariablesColumn, ResultRepoURLColumn, ApprovedAtColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{IDColumn, VariablesColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return scaffoldRequestsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		ProjectID:     ProjectIDColumn,
		RequestedBy:   RequestedByColumn,
		ApprovedBy:    ApprovedByColumn,
		Status:        StatusColumn,
		Variables:     VariablesColumn,
		ResultRepoURL: ResultRepoURLColumn,
		ApprovedAt:    ApprovedAtColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
