//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ScaffoldRequests = newScaffoldRequestsTable("public", "scaffold_requests", "")

type scaffoldRequestsTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	PluginID      postgres.ColumnString
	Template      postgres.ColumnString
	RequestedBy   postgres.ColumnString
	Status        postgres.ColumnString
	ProjectID     postgres.ColumnString
	Environment   postgres.ColumnString
	Variables     postgres.ColumnString
	ApprovedBy    postgres.ColumnString
	ResultRepoURL postgres.ColumnString
	ApprovedAt    postgres.ColumnTimestamp
	CreatedAt     postgres.ColumnTimestamp
	UpdatedAt     postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ScaffoldRequestsTable struct {
	scaffoldRequestsTable

	EXCLUDED scaffoldRequestsTable
}

// AS creates new ScaffoldRequestsTable with assigned alias
func (a ScaffoldRequestsTable) AS(alias string) *ScaffoldRequestsTable {
	return newScaffoldRequestsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ScaffoldRequestsTable with assigned schema name
func (a ScaffoldRequestsTable) FromSchema(schemaName string) *ScaffoldRequestsTable {
	return newScaffoldRequestsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ScaffoldRequestsTable with assigned table prefix
func (a ScaffoldRequestsTable) WithPrefix(prefix string) *ScaffoldRequestsTable {
	return newScaffoldRequestsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ScaffoldRequestsTable with assigned table suffix
func (a ScaffoldRequestsTable) WithSuffix(suffix string) *ScaffoldRequestsTable {
	return newScaffoldRequestsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newScaffoldRequestsTable(schemaName, tableName, alias string) *ScaffoldRequestsTable {
	return &ScaffoldRequestsTable{
		scaffoldRequestsTable: newScaffoldRequestsTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newScaffoldRequestsTableImpl("", "excluded", ""),
	}
}

func newScaffoldRequestsTableImpl(schemaName, tableName, alias string) scaffoldRequestsTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		PluginIDColumn      = postgres.StringColumn("plugin_id")
		TemplateColumn      = postgres.StringColumn("template")
		RequestedByColumn   = postgres.StringColumn("requested_by")
		StatusColumn        = postgres.StringColumn("status")
		ProjectIDColumn     = postgres.StringColumn("project_id")
		EnvironmentColumn   = postgres.StringColumn("environment")
		VariablesColumn     = postgres.StringColumn("variables")
		ApprovedByColumn    = postgres.StringColumn("approved_by")
		ResultRepoURLColumn = postgres.StringColumn("result_repo_url")
		ApprovedAtColumn    = postgres.TimestampColumn("approved_at")
		CreatedAtColumn     = postgres.TimestampColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampColumn("updated_at")
		allColumns          = postgres.ColumnList{IDColumn, PluginIDColumn, TemplateColumn, RequestedByColumn, StatusColumn, ProjectIDColumn, EnvironmentColumn, VariablesColumn, ApprovedByColumn, ResultRepoURLColumn, ApprovedAtColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{PluginIDColumn, TemplateColumn, RequestedByColumn, StatusColumn, ProjectIDColumn, EnvironmentColumn, VariablesColumn, ApprovedByColumn, ResultRepoURLColumn, ApprovedAtColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return scaffoldRequestsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		PluginID:      PluginIDColumn,
		Template:      TemplateColumn,
		RequestedBy:   RequestedByColumn,
		Status:        StatusColumn,
		ProjectID:     ProjectIDColumn,
		Environment:   EnvironmentColumn,
		Variables:     VariablesColumn,
		ApprovedBy:    ApprovedByColumn,
		ResultRepoURL: ResultRepoURLColumn,
		ApprovedAt:    ApprovedAtColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
