//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ScaffoldRequests = newScaffoldRequestsTable("public", "scaffold_requests", "")

type scaffoldRequestsTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	Template    postgres.ColumnString
	ProjectID   postgres.ColumnString
	Environment postgres.ColumnString
	Variables   postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ScaffoldRequestsTable struct {
	scaffoldRequestsTable

	EXCLUDED scaffoldRequestsTable
}

// AS creates new ScaffoldRequestsTable with assigned alias
func (a ScaffoldRequestsTable) AS(alias string) *ScaffoldRequestsTable {
	return newScaffoldRequestsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ScaffoldRequestsTable with assigned schema name
func (a ScaffoldRequestsTable) FromSchema(schemaName string) *ScaffoldRequestsTable {
	return newScaffoldRequestsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ScaffoldRequestsTable with assigned table prefix
func (a ScaffoldRequestsTable) WithPrefix(prefix string) *ScaffoldRequestsTable {
	return newScaffoldRequestsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ScaffoldRequestsTable with assigned table suffix
func (a ScaffoldRequestsTable) WithSuffix(suffix string) *ScaffoldRequestsTable {
	return newScaffoldRequestsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newScaffoldRequestsTable(schemaName, tableName, alias string) *ScaffoldRequestsTable {
	return &ScaffoldRequestsTable{
		scaffoldRequestsTable: newScaffoldRequestsTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newScaffoldRequestsTableImpl("", "excluded", ""),
	}
}

func newScaffoldRequestsTableImpl(schemaName, tableName, alias string) scaffoldRequestsTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		TemplateColumn    = postgres.StringColumn("template")
		ProjectIDColumn   = postgres.StringColumn("project_id")
		EnvironmentColumn = postgres.StringColumn("environment")
		VariablesColumn   = postgres.StringColumn("variables")
		allColumns        = postgres.ColumnList{IDColumn, TemplateColumn, ProjectIDColumn, EnvironmentColumn, VariablesColumn}
		mutableColumns    = postgres.ColumnList{TemplateColumn, ProjectIDColumn, EnvironmentColumn, VariablesColumn}
		defaultColumns    = postgres.ColumnList{IDColumn}
	)

	return scaffoldRequestsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Template:    TemplateColumn,
		ProjectID:   ProjectIDColumn,
		Environment: EnvironmentColumn,
		Variables:   VariablesColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
