//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ServiceDependencies = newServiceDependenciesTable("public", "service_dependencies", "")

type serviceDependenciesTable struct {
	postgres.Table

	// Columns
	ID                 postgres.ColumnString
	ServiceID          postgres.ColumnString
	DependsOnServiceID postgres.ColumnString
	Type               postgres.ColumnString
	Protocol           postgres.ColumnString
	Port               postgres.ColumnInteger
	Path               postgres.ColumnString
	Config             postgres.ColumnString
	CreatedBy          postgres.ColumnString
	CreatedAt          postgres.ColumnTimestamp
	UpdatedAt          postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ServiceDependenciesTable struct {
	serviceDependenciesTable

	EXCLUDED serviceDependenciesTable
}

// AS creates new ServiceDependenciesTable with assigned alias
func (a ServiceDependenciesTable) AS(alias string) *ServiceDependenciesTable {
	return newServiceDependenciesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ServiceDependenciesTable with assigned schema name
func (a ServiceDependenciesTable) FromSchema(schemaName string) *ServiceDependenciesTable {
	return newServiceDependenciesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ServiceDependenciesTable with assigned table prefix
func (a ServiceDependenciesTable) WithPrefix(prefix string) *ServiceDependenciesTable {
	return newServiceDependenciesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ServiceDependenciesTable with assigned table suffix
func (a ServiceDependenciesTable) WithSuffix(suffix string) *ServiceDependenciesTable {
	return newServiceDependenciesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newServiceDependenciesTable(schemaName, tableName, alias string) *ServiceDependenciesTable {
	return &ServiceDependenciesTable{
		serviceDependenciesTable: newServiceDependenciesTableImpl(schemaName, tableName, alias),
		EXCLUDED:                 newServiceDependenciesTableImpl("", "excluded", ""),
	}
}

func newServiceDependenciesTableImpl(schemaName, tableName, alias string) serviceDependenciesTable {
	var (
		IDColumn                 = postgres.StringColumn("id")
		ServiceIDColumn          = postgres.StringColumn("service_id")
		DependsOnServiceIDColumn = postgres.StringColumn("depends_on_service_id")
		TypeColumn               = postgres.StringColumn("type")
		ProtocolColumn           = postgres.StringColumn("protocol")
		PortColumn               = postgres.IntegerColumn("port")
		PathColumn               = postgres.StringColumn("path")
		ConfigColumn             = postgres.StringColumn("config")
		CreatedByColumn          = postgres.StringColumn("created_by")
		CreatedAtColumn          = postgres.TimestampColumn("created_at")
		UpdatedAtColumn          = postgres.TimestampColumn("updated_at")
		allColumns               = postgres.ColumnList{IDColumn, ServiceIDColumn, DependsOnServiceIDColumn, TypeColumn, ProtocolColumn, PortColumn, PathColumn, ConfigColumn, CreatedByColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns           = postgres.ColumnList{ServiceIDColumn, DependsOnServiceIDColumn, TypeColumn, ProtocolColumn, PortColumn, PathColumn, ConfigColumn, CreatedByColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns           = postgres.ColumnList{IDColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return serviceDependenciesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                 IDColumn,
		ServiceID:          ServiceIDColumn,
		DependsOnServiceID: DependsOnServiceIDColumn,
		Type:               TypeColumn,
		Protocol:           ProtocolColumn,
		Port:               PortColumn,
		Path:               PathColumn,
		Config:             ConfigColumn,
		CreatedBy:          CreatedByColumn,
		CreatedAt:          CreatedAtColumn,
		UpdatedAt:          UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
