//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Services = newServicesTable("public", "services", "")

type servicesTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	ProjectID postgres.ColumnString
	Name      postgres.ColumnString
	RepoURL   postgres.ColumnString
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp
	DeletedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ServicesTable struct {
	servicesTable

	EXCLUDED servicesTable
}

// AS creates new ServicesTable with assigned alias
func (a ServicesTable) AS(alias string) *ServicesTable {
	return newServicesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ServicesTable with assigned schema name
func (a ServicesTable) FromSchema(schemaName string) *ServicesTable {
	return newServicesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ServicesTable with assigned table prefix
func (a ServicesTable) WithPrefix(prefix string) *ServicesTable {
	return newServicesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ServicesTable with assigned table suffix
func (a ServicesTable) WithSuffix(suffix string) *ServicesTable {
	return newServicesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newServicesTable(schemaName, tableName, alias string) *ServicesTable {
	return &ServicesTable{
		servicesTable: newServicesTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newServicesTableImpl("", "excluded", ""),
	}
}

func newServicesTableImpl(schemaName, tableName, alias string) servicesTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		ProjectIDColumn = postgres.StringColumn("project_id")
		NameColumn      = postgres.StringColumn("name")
		RepoURLColumn   = postgres.StringColumn("repo_url")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		DeletedAtColumn = postgres.TimestampColumn("deleted_at")
		allColumns      = postgres.ColumnList{IDColumn, ProjectIDColumn, NameColumn, RepoURLColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		mutableColumns  = postgres.ColumnList{ProjectIDColumn, NameColumn, RepoURLColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		defaultColumns  = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return servicesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		ProjectID: ProjectIDColumn,
		Name:      NameColumn,
		RepoURL:   RepoURLColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,
		DeletedAt: DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
