//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Teams = newTeamsTable("public", "teams", "")

type teamsTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	Name         postgres.ColumnString
	OwnerContact postgres.ColumnString
	CreatedAt    postgres.ColumnTimestamp
	UpdatedAt    postgres.ColumnTimestamp
	DeletedAt    postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TeamsTable struct {
	teamsTable

	EXCLUDED teamsTable
}

// AS creates new TeamsTable with assigned alias
func (a TeamsTable) AS(alias string) *TeamsTable {
	return newTeamsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TeamsTable with assigned schema name
func (a TeamsTable) FromSchema(schemaName string) *TeamsTable {
	return newTeamsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TeamsTable with assigned table prefix
func (a TeamsTable) WithPrefix(prefix string) *TeamsTable {
	return newTeamsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TeamsTable with assigned table suffix
func (a TeamsTable) WithSuffix(suffix string) *TeamsTable {
	return newTeamsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTeamsTable(schemaName, tableName, alias string) *TeamsTable {
	return &TeamsTable{
		teamsTable: newTeamsTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newTeamsTableImpl("", "excluded", ""),
	}
}

func newTeamsTableImpl(schemaName, tableName, alias string) teamsTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		NameColumn         = postgres.StringColumn("name")
		OwnerContactColumn = postgres.StringColumn("owner_contact")
		CreatedAtColumn    = postgres.TimestampColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampColumn("updated_at")
		DeletedAtColumn    = postgres.TimestampColumn("deleted_at")
		allColumns         = postgres.ColumnList{IDColumn, NameColumn, OwnerContactColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		mutableColumns     = postgres.ColumnList{NameColumn, OwnerContactColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return teamsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		Name:         NameColumn,
		OwnerContact: OwnerContactColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,
		DeletedAt:    DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
