-- 202512062050_init.down.sql
DROP TABLE IF EXISTS releases;
DROP TABLE IF EXISTS scaffold_requests;
DROP TABLE IF EXISTS deployments;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS plugins;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS teams;
