//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type ApprovalDecisions struct {
	ID                uuid.UUID `sql:"primary_key" db:"approval_decisions.id"`
	ApprovalRequestID uuid.UUID `db:"approval_decisions.approval_request_id"`
	DecidedBy         uuid.UUID `db:"approval_decisions.decided_by"`
	Decision          string    `db:"approval_decisions.decision"`
	Comment           *string   `db:"approval_decisions.comment"`
	CreatedAt         time.Time `db:"approval_decisions.created_at"`
}
