//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type ApprovalRequests struct {
	ID                uuid.UUID  `sql:"primary_key" db:"approval_requests.id"`
	Resource          string     `db:"approval_requests.resource"`
	Action            string     `db:"approval_requests.action"`
	ResourceID        uuid.UUID  `db:"approval_requests.resource_id"`
	RequestedBy       uuid.UUID  `db:"approval_requests.requested_by"`
	ProjectID         *uuid.UUID `db:"approval_requests.project_id"`
	ServiceID         *uuid.UUID `db:"approval_requests.service_id"`
	Environment       *string    `db:"approval_requests.environment"`
	Status            string     `db:"approval_requests.status"`
	RequiredApprovals int32      `db:"approval_requests.required_approvals"`
	ApprovedCount     int32      `db:"approval_requests.approved_count"`
	RejectedCount     int32      `db:"approval_requests.rejected_count"`
	ResolvedAt        *time.Time `db:"approval_requests.resolved_at"`
	CreatedAt         time.Time  `db:"approval_requests.created_at"`
	UpdatedAt         time.Time  `db:"approval_requests.updated_at"`
}
