//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Deployments struct {
	ID          uuid.UUID `sql:"primary_key" db:"deployments.id"`
	ProjectID   uuid.UUID `db:"deployments.project_id"`
	Environment string    `db:"deployments.environment"`
	Service     string    `db:"deployments.service"`
	Version     string    `db:"deployments.version"`
	Status      string    `db:"deployments.status"`
	TriggeredBy uuid.UUID `db:"deployments.triggered_by"`
	CreatedAt   time.Time `db:"deployments.created_at"`
}
