//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Deployments struct {
	ID            uuid.UUID  `sql:"primary_key" db:"deployments.id"`
	ServiceID     uuid.UUID  `db:"deployments.service_id"`
	EnvironmentID uuid.UUID  `db:"deployments.environment_id"`
	ReleaseID     uuid.UUID  `db:"deployments.release_id"`
	PluginID      uuid.UUID  `db:"deployments.plugin_id"`
	Status        string     `db:"deployments.status"`
	ExternalRef   *string    `db:"deployments.external_ref"`
	CommitSha     *string    `db:"deployments.commit_sha"`
	TriggeredBy   uuid.UUID  `db:"deployments.triggered_by"`
	CreatedAt     time.Time  `db:"deployments.created_at"`
	UpdatedAt     time.Time  `db:"deployments.updated_at"`
	StartedAt     *time.Time `db:"deployments.started_at"`
	FinishedAt    *time.Time `db:"deployments.finished_at"`
}
