//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Environments struct {
	ID             uuid.UUID `sql:"primary_key" db:"environments.id"`
	ProjectID      uuid.UUID `db:"environments.project_id"`
	Name           string    `db:"environments.name"`
	Tier           string    `db:"environments.tier"`
	Cluster        string    `db:"environments.cluster"`
	Namespace      string    `db:"environments.namespace"`
	ArgocdInstance string    `db:"environments.argocd_instance"`
	Config         string    `db:"environments.config"`
	CreatedAt      time.Time `db:"environments.created_at"`
	UpdatedAt      time.Time `db:"environments.updated_at"`
}
