//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Jobs struct {
	ID           uuid.UUID  `sql:"primary_key" db:"jobs.id"`
	Type         string     `db:"jobs.type"`
	Status       string     `db:"jobs.status"`
	ResourceType string     `db:"jobs.resource_type"`
	ResourceID   uuid.UUID  `db:"jobs.resource_id"`
	PluginID     uuid.UUID  `db:"jobs.plugin_id"`
	Payload      string     `db:"jobs.payload"`
	Result       string     `db:"jobs.result"`
	Error        *string    `db:"jobs.error"`
	Attempts     int32      `db:"jobs.attempts"`
	MaxAttempts  int32      `db:"jobs.max_attempts"`
	CreatedBy    uuid.UUID  `db:"jobs.created_by"`
	CreatedAt    time.Time  `db:"jobs.created_at"`
	UpdatedAt    time.Time  `db:"jobs.updated_at"`
	StartedAt    *time.Time `db:"jobs.started_at"`
	FinishedAt   *time.Time `db:"jobs.finished_at"`
}
