//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Plugins struct {
	ID          uuid.UUID `sql:"primary_key" db:"plugins.id"`
	Name        string    `db:"plugins.name"`
	Version     string    `db:"plugins.version"`
	Type        string    `db:"plugins.type"`
	Runtime     string    `db:"plugins.runtime"`
	Entrypoint  string    `db:"plugins.entrypoint"`
	Enabled     bool      `db:"plugins.enabled"`
	Scope       string    `db:"plugins.scope"`
	Description *string   `db:"plugins.description"`
	InstalledAt time.Time `db:"plugins.installed_at"`
}
