//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Projects struct {
	ID          uuid.UUID `sql:"primary_key" db:"projects.id"`
	Name        string    `db:"projects.name"`
	Description *string   `db:"projects.description"`
	OwnerTeamID uuid.UUID `db:"projects.owner_team_id"`
	CreatedBy   uuid.UUID `db:"projects.created_by"`
	CreatedAt   time.Time `db:"projects.created_at"`
	UpdatedAt   time.Time `db:"projects.updated_at"`
}
