//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type RefreshTokens struct {
	ID        uuid.UUID  `sql:"primary_key" db:"refresh_tokens.id"`
	UserID    uuid.UUID  `db:"refresh_tokens.user_id"`
	Token     string     `db:"refresh_tokens.token"`
	CreatedAt time.Time  `db:"refresh_tokens.created_at"`
	ExpiresAt time.Time  `db:"refresh_tokens.expires_at"`
	DeletedAt *time.Time `db:"refresh_tokens.deleted_at"`
}
