//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Releases struct {
	ID          uuid.UUID `sql:"primary_key" db:"releases.id"`
	ProjectID   uuid.UUID `db:"releases.project_id"`
	Tag         string    `db:"releases.tag"`
	Target      string    `db:"releases.target"`
	Name        string    `db:"releases.name"`
	Notes       string    `db:"releases.notes"`
	HTMLURL     string    `db:"releases.html_url"`
	ExternalRef string    `db:"releases.external_ref"`
	TriggeredBy uuid.UUID `db:"releases.triggered_by"`
	CreatedAt   time.Time `db:"releases.created_at"`
}
