//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type RolePermissions struct {
	ID           uuid.UUID `sql:"primary_key" db:"role_permissions.id"`
	RoleID       uuid.UUID `db:"role_permissions.role_id"`
	PermissionID uuid.UUID `db:"role_permissions.permission_id"`
	CreatedAt    time.Time `db:"role_permissions.created_at"`
}
