//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Services struct {
	ID        uuid.UUID  `sql:"primary_key" db:"services.id"`
	ProjectID uuid.UUID  `db:"services.project_id"`
	Name      string     `db:"services.name"`
	RepoURL   string     `db:"services.repo_url"`
	CreatedAt time.Time  `db:"services.created_at"`
	UpdatedAt time.Time  `db:"services.updated_at"`
	DeletedAt *time.Time `db:"services.deleted_at"`
}
