//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type ServiceDependencies struct {
	ID                 uuid.UUID `sql:"primary_key" db:"service_dependencies.id"`
	ServiceID          uuid.UUID `db:"service_dependencies.service_id"`
	DependsOnServiceID uuid.UUID `db:"service_dependencies.depends_on_service_id"`
	Type               string    `db:"service_dependencies.type"`
	Protocol           *string   `db:"service_dependencies.protocol"`
	Port               *int32    `db:"service_dependencies.port"`
	Path               *string   `db:"service_dependencies.path"`
	Config             string    `db:"service_dependencies.config"`
	CreatedBy          uuid.UUID `db:"service_dependencies.created_by"`
	CreatedAt          time.Time `db:"service_dependencies.created_at"`
	UpdatedAt          time.Time `db:"service_dependencies.updated_at"`
}
