//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Teams struct {
	ID           uuid.UUID  `sql:"primary_key" db:"teams.id"`
	Name         string     `db:"teams.name"`
	OwnerContact string     `db:"teams.owner_contact"`
	CreatedAt    time.Time  `db:"teams.created_at"`
	UpdatedAt    time.Time  `db:"teams.updated_at"`
	DeletedAt    *time.Time `db:"teams.deleted_at"`
}
