//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UserRoles struct {
	ID        uuid.UUID `sql:"primary_key" db:"user_roles.id"`
	UserID    uuid.UUID `db:"user_roles.user_id"`
	RoleID    uuid.UUID `db:"user_roles.role_id"`
	CreatedAt time.Time `db:"user_roles.created_at"`
}
