//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Users struct {
	ID           uuid.UUID  `sql:"primary_key" db:"users.id"`
	Name         string     `db:"users.name"`
	Email        string     `db:"users.email"`
	PasswordHash string     `db:"users.password_hash"`
	Role         string     `db:"users.role"`
	CreatedAt    time.Time  `db:"users.created_at"`
	UpdatedAt    time.Time  `db:"users.updated_at"`
	DeletedAt    *time.Time `db:"users.deleted_at"`
}
