import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import (  # noqa: E402
    build_scaffold_output,
    read_int,
    read_payload,
    read_required_str,
    resolve_container_image,
    resolve_service_dir,
    success,
    validate_service_name,
)

SCHEMA_PATH = Path(__file__).with_name("schema.json")


def load_schema() -> dict:
    return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))


def write_files(service_dir: Path, service_name: str, port: int, image: str) -> None:
    (service_dir / "package.json").write_text(
        json.dumps(
            {
                "name": service_name,
                "version": "0.1.0",
                "private": True,
                "type": "module",
                "scripts": {
                    "dev": "node src/index.js",
                    "start": "node src/index.js",
                },
                "dependencies": {
                    "express": "^4.21.2",
                },
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    src_dir = service_dir / "src"
    src_dir.mkdir(parents=True, exist_ok=True)
    (src_dir / "index.js").write_text(
        f"""import express from "express";

const app = express();
const port = process.env.PORT || {port};

app.get("/healthz", (_req, res) => {{
  res.json({{ status: "ok", service: "{service_name}" }});
}});

app.listen(port, () => {{
  console.log("{service_name} listening on port " + port);
}});
""",
        encoding="utf-8",
    )

    (service_dir / ".gitignore").write_text(
        """node_modules/
dist/
.env
""",
        encoding="utf-8",
    )

    (service_dir / "README.md").write_text(
        f"""# {service_name}

Minimal Node.js HTTP API generated by DevHub plugin.

## Run

```bash
npm install
npm run dev
```

## Endpoint

- `GET /healthz`
""",
        encoding="utf-8",
    )

    (service_dir / "Dockerfile").write_text(
        """FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "run", "start"]
""",
        encoding="utf-8",
    )

    k8s_dir = service_dir / "k8s"
    k8s_dir.mkdir(parents=True, exist_ok=True)
    (k8s_dir / "deployment.yaml").write_text(
        f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: {service_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {service_name}
  template:
    metadata:
      labels:
        app: {service_name}
    spec:
      containers:
        - name: {service_name}
          image: {image}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {port}
          env:
            - name: PORT
              value: "{port}"
""",
        encoding="utf-8",
    )
    (k8s_dir / "service.yaml").write_text(
        f"""apiVersion: v1
kind: Service
metadata:
  name: {service_name}
spec:
  selector:
    app: {service_name}
  ports:
    - name: http
      port: {port}
      targetPort: {port}
""",
        encoding="utf-8",
    )
    (k8s_dir / "kustomization.yaml").write_text(
        """apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
""",
        encoding="utf-8",
    )


def main() -> None:
    schema = load_schema()
    payload = read_payload(required_fields=schema.get("required", ["service_name"]))
    properties = schema.get("properties", {})

    service_name = read_required_str(payload, "service_name")
    project_id = str(payload.get("project_id", "")).strip()
    output_dir_raw = str(payload.get("output_dir", "")).strip()
    port = read_int(
        payload,
        "port",
        default=properties.get("port", {}).get("default", 3000),
        min_value=1,
        max_value=65535,
    )

    if output_dir_raw == "":
        base_dir = Path("/app/generated")
        output_dir_raw = str(base_dir / project_id) if project_id else str(base_dir)

    validate_service_name(service_name)
    service_dir = resolve_service_dir(output_dir_raw, service_name)
    image = resolve_container_image(payload, service_name)
    write_files(service_dir, service_name, port, image)

    success(build_scaffold_output(service_dir, service_name, payload))


if __name__ == "__main__":
    main()
