{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride | default .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.fullnameOverride | default .Chart.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
{{- end }}
