/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const formatOptionalDate: typeof import('./utils/date').formatOptionalDate
  const formatRequestedAt: typeof import('./utils/date').formatRequestedAt
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly formatOptionalDate: UnwrapRef<typeof import('./utils/date')['formatOptionalDate']>
    readonly formatRequestedAt: UnwrapRef<typeof import('./utils/date')['formatRequestedAt']>
  }
}