apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devhub.fullname" . }}-secret
  labels:
    {{- include "devhub.labels" . | nindent 4 }}
type: Opaque
stringData:
  TOKEN_SECRET: {{ .Values.secrets.tokenSecret | quote }}
  ARGOCD_AUTH_TOKEN: {{ .Values.secrets.argocdAuthToken | quote }}
